spring:
    main: 
      allow-bean-definition-overriding: true
    application:
      name: licensing-service 
    profiles:
      active: dev 
    config: 
      import: "optional:configserver:http://localhost:8071"
