spring:
    main: 
      allow-bean-definition-overriding: true
    application:
      name: licensing-service 
    profiles:
      active: dev
    config: 
      import: "optional:configserver:http://192.168.5.7:8071"
